//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.QRTZ
{
	public class Virtual_QRTZ_SIMPLE_TRIGGERSModel
	{
			public virtual string SCHED_NAME { get; set; }
			public virtual string TRIGGER_NAME { get; set; }
			public virtual string TRIGGER_GROUP { get; set; }
			public virtual int REPEAT_COUNT { get; set; }
			public virtual long REPEAT_INTERVAL { get; set; }
			public virtual int TIMES_TRIGGERED { get; set; }
		}
}
