//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.QRTZ
{
	public class Virtual_QRTZ_SIMPROP_TRIGGERSModel
	{
			public virtual string SCHED_NAME { get; set; }
			public virtual string TRIGGER_NAME { get; set; }
			public virtual string TRIGGER_GROUP { get; set; }
			public virtual string STR_PROP_1 { get; set; }
			public virtual string STR_PROP_2 { get; set; }
			public virtual string STR_PROP_3 { get; set; }
			public virtual Nullable<int> INT_PROP_1 { get; set; }
			public virtual Nullable<int> INT_PROP_2 { get; set; }
			public virtual Nullable<long> LONG_PROP_1 { get; set; }
			public virtual Nullable<long> LONG_PROP_2 { get; set; }
			public virtual Nullable<decimal> DEC_PROP_1 { get; set; }
			public virtual Nullable<decimal> DEC_PROP_2 { get; set; }
			public virtual Nullable<bool> BOOL_PROP_1 { get; set; }
			public virtual Nullable<bool> BOOL_PROP_2 { get; set; }
		}
}
