//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.QRTZ
{
	public class Virtual_QRTZ_FIRED_TRIGGERSModel
	{
			public virtual string SCHED_NAME { get; set; }
			public virtual string ENTRY_ID { get; set; }
			public virtual string TRIGGER_NAME { get; set; }
			public virtual string TRIGGER_GROUP { get; set; }
			public virtual string INSTANCE_NAME { get; set; }
			public virtual long FIRED_TIME { get; set; }
			public virtual long SCHED_TIME { get; set; }
			public virtual int PRIORITY { get; set; }
			public virtual string STATE { get; set; }
			public virtual string JOB_NAME { get; set; }
			public virtual string JOB_GROUP { get; set; }
			public virtual Nullable<bool> IS_NONCONCURRENT { get; set; }
			public virtual Nullable<bool> REQUESTS_RECOVERY { get; set; }
		}
}
