//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.QRTZ
{
	public class Virtual_QRTZ_JOB_DETAILSModel
	{
			public virtual string SCHED_NAME { get; set; }
			public virtual string JOB_NAME { get; set; }
			public virtual string JOB_GROUP { get; set; }
			public virtual string DESCRIPTION { get; set; }
			public virtual string JOB_CLASS_NAME { get; set; }
			public virtual bool IS_DURABLE { get; set; }
			public virtual bool IS_NONCONCURRENT { get; set; }
			public virtual bool IS_UPDATE_DATA { get; set; }
			public virtual bool REQUESTS_RECOVERY { get; set; }
			public virtual byte[] JOB_DATA { get; set; }
		}
}
